# ═══════════════════════════════════════════════════════════════
# fte_sdk / models / social.py
#
# PURPOSE: Social media models — Instagram/Facebook post
#          scheduling aur comment engagement ke liye.
#
# USED BY: content_scheduling (CRUD), comment_engagement (CRUD)
# ═══════════════════════════════════════════════════════════════

from sqlalchemy import (
    Column, Integer, String, Text, Boolean, DateTime,
    ForeignKey, func,
)
from sqlalchemy.orm import relationship

from src.sdk.database import Base


# ─── SocialAccount ─────────────────────────────────────────────
# Connected social media account (Instagram / Facebook / TikTok / LinkedIn).
# access_token = Platform API token. store_id = Shopify store.

class SocialAccount(Base):
    __tablename__ = "social_accounts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    store_id = Column(Integer, ForeignKey("stores.id"), nullable=False, index=True)
    platform = Column(String(50), nullable=False)          # "instagram" | "facebook" | "tiktok" | "linkedin"
    account_name = Column(String(255), nullable=False)
    account_id = Column(String(255), default="")           # Platform-specific account/page ID
    access_token = Column(String(512), nullable=False)
    refresh_token = Column(String(512), default="")
    token_expires_at = Column(DateTime(timezone=True), nullable=True)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())


# ─── ScheduledPost ───────────────────────────────────────────
# Post scheduled for publishing on a social platform.
# content_generation creates → content_scheduling publishes.

class ScheduledPost(Base):
    __tablename__ = "scheduled_posts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    social_account_id = Column(Integer, ForeignKey("social_accounts.id"), nullable=False, index=True)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=True)
    generated_post_id = Column(Integer, ForeignKey("generated_posts.id"), nullable=True)
    caption = Column(Text, default="")
    media_urls = Column(Text, default="")                   # JSON array of URLs
    platform = Column(String(50), nullable=False)
    platform_post_id = Column(String(255), nullable=True)   # Native platform post ID
    scheduled_at = Column(DateTime(timezone=True), nullable=False)
    status = Column(String(50), default="draft")            # draft | scheduled | publishing | published | failed | permanently_failed
    retry_count = Column(Integer, default=0)                # Max 3 retries
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    published_at = Column(DateTime(timezone=True), nullable=True)


# ─── Comment ──────────────────────────────────────────────────
# Incoming comment from social media platform. Generated by
# comment_engagement. May trigger Reply.

class Comment(Base):
    __tablename__ = "comments"

    id = Column(Integer, primary_key=True, autoincrement=True)
    social_account_id = Column(Integer, ForeignKey("social_accounts.id"), nullable=False, index=True)
    platform_post_id = Column(String(255), nullable=False)
    author = Column(String(255), default="")
    text = Column(Text, default="")
    sentiment = Column(String(50), default="neutral")       # positive | neutral | negative
    is_escalated = Column(Boolean, default=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    replies = relationship("Reply", back_populates="comment", cascade="all, delete-orphan")


# ─── Reply ────────────────────────────────────────────────────
# Agent-generated reply to a Comment. content_generation creates
# draft → comment_engagement posts it.

class Reply(Base):
    __tablename__ = "replies"

    id = Column(Integer, primary_key=True, autoincrement=True)
    comment_id = Column(Integer, ForeignKey("comments.id"), nullable=False, index=True)
    text = Column(Text, default="")
    status = Column(String(50), default="draft")             # draft | approved | posted | rejected
    generated_by_llm = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    posted_at = Column(DateTime(timezone=True), nullable=True)

    comment = relationship("Comment", back_populates="replies")
